WITH RECURSIVE TEMP(A) AS(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT A + 1 
    FROM TEMP
    WHERE A + 1 <24
)

SELECT T.A, COUNT(A.DATETIME) AS 'COUNT'
FROM TEMP T LEFT JOIN ANIMAL_OUTS A
    ON HOUR(A.DATETIME) = T.A
GROUP BY T.A
ORDER BY 1