SELECT TITLE, a.BOARD_ID, REPLY_ID, b.WRITER_ID, b.CONTENTS, DATE_FORMAT(b.CREATED_DATE,"%Y-%m-%d") AS CREATED_DATE
FROM USED_GOODS_BOARD a
RIGHT JOIN USED_GOODS_REPLY b
ON a.BOARD_ID = b.BOARD_ID
WHERE a.CREATED_DATE LIKE "2022-10%"
ORDER BY CREATED_DATE ASC, TITLE ASC